language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - pypy

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

install:
  - make dev
  - pip install coveralls

script:
  - py.test --cov=relief/ --cov=tests/
  - sphinx-build -aEWb doctest docs docs/_build

after_success:
  - coveralls
