language: python
python:
  - 2.7
  - 3.3
  - pypy
install:
  - python setup.py install
  - pip install pyflakes
  - pip install sphinx
script:
  - find relief -iname "*.py" | xargs pyflakes
  - py.test -vv relief
  - sphinx-build -aEWb linkcheck docs docs/_build
