language: python
python:
  - 2.7
  - 3.3
#  - pypy we require at least pypy >= 2.0 travis doesn't it, yet.
install:
  - python setup.py install
  - pip install --use-mirrors pyflakes
  - pip install --use-mirrors sphinx==1.1.3
script:
  - find relief -iname "*.py" | xargs pyflakes
  - py.test -vv relief
  - sphinx-build -aEWb linkcheck docs docs/_build
  - sphinx-build -aEWb doctest docs docs/_build
