language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - pypy

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

install:
  - make dev

script:
  - py.test
  - sphinx-build -aEWb doctest docs docs/_build
