language: python

python:
  - 2.6
  - 2.7
  - 3.3
#  - pypy we require at least pypy >= 2.0 travis doesn't support it, yet.

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

install:
  - make dev

script:
  - py.test -vv relief
  - sphinx-build -aEWb doctest docs docs/_build
